### ISSUE TITLE
How to run the jython files?

### ISSUE THREAD

**Issue by cubetastic33** [thewca/tnoodle#341]
When I ran ./tmt make check, and I got the following result:
```
$ ./tmt make check
svglite is up to date, not recompiling
utils is up to date, not recompiling
web-utils is up to date, not recompiling
winstone is up to date, not recompiling
quercus is up to date, not recompiling
hello-winstone is up to date, not recompiling
sq12phase is up to date, not recompiling
min2phase is up to date, not recompiling
threephase is up to date, not recompiling
scrambles is up to date, not recompiling
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.RuntimeException: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
	at com.android.build.gradle.internal.SdkHandler.getAndCheckSdkFolder(SdkHandler.java:102)
	at com.android.build.gradle.internal.SdkHandler.getSdkLoader(SdkHandler.java:112)
	at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:86)
	at com.android.build.gradle.BasePlugin.ensureTargetSetup(BasePlugin.java:673)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:610)
	at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:566)
	at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:563)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
	at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:562)
	at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:559)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:532)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pi/Desktop/tnoodle/tnoodle-android/library/build.gradle' line: 52

* What went wrong:
A problem occurred evaluating project ':library'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 46.744 secs
Hit excepthook! stderr.isatty: True stdin.isatty: True stdout.isatty: True
Traceback (most recent call last):
  File "./tmt", line 1220, in <module>
    tmt._main()
  File "./tmt", line 231, in _main
    self.args.func()
  File "./tmt", line 287, in _make
    tmt._make(projectName=project.name, command='compile')
  File "./tmt", line 293, in _make
    commandFunc()
  File "tnoodle-android/tmtproject.py", line 17, in compile
    self.runGradleTask("assemble")
  File "tnoodle-android/tmtproject.py", line 14, in runGradleTask
    assert retVal == 0
AssertionError
> /home/pi/Desktop/tnoodle/tnoodle-android/tmtproject.py(14)runGradleTask()
-> assert retVal == 0
```
Also, I am not able to run the jython test files because of this...

**Comment by jfly** [comment]
Two thoughts:

1. You're trying to build `tnoodle-android`, which you probably don't need for what you're doing. Running something like `./tmt make check -p webscrambles` should probably skip that.
2. There appears to be some useful error output from the command you ran, I'd suggest actually reading it and trying to follow the instructions.

3. If you really just want to generate scrambles in python, I think a better solution would be to run TNoodle on your Raspeberry PI, and use the TNoodle API to request scrambles over HTTP. To get more information about the TNoodle API, simply run TNoodle on your computer and visit http://localhost:2014/readme.

**Comment by campos20** [comment]
I'm not very familiar with Raspberry yet, but in your place, I think I'd generate a scrambles module (like scrambles.jar) and use its output. You can call `java -jar scrambles.jar 333` and get nice 3x3x3 scrambles. The output can be used in python or whatever you want.

**Comment by jfly** [comment]
@campos20, that would work, but be a lot slower than what I suggest. If you use the server, you won't have to wait for TNoodle to start up each time you want a scramble.

**Comment by cubetastic33** [comment]
@jfly well, I want my raspberry pi to work offline, so that's why I decided web scraping isn't an option. Also, what do you mean run TNoodle? The main reason I'm asking so many questions to you without figuring it out myself if because I know absolutely no java. Also, jython, too, seems to be very slow on the pi... I googled this error:
`SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`
And looks like I need to do something with android studio. But, the README said that everything was an eclipse workspace. I generally work with VS Code, and I couldn't figure this out, so I decided to ask you...

**Comment by jfly** [comment]
I'm not suggesting doing anything over the internet, nor am I suggesting doing any web scraping. Just start tnoodle on your raspberry pi and talk directly to its api.

If this doesn't make sense, I suggest that you try running tnoodle on your personal computer while you are disconnected from the internet and try to understand how it works.

**Comment by cubetastic33** [comment]
I'm sorry for this really silly question, but does "run tnoodle" mean executing `./tmt make check`? :smile:

**Comment by cubetastic33** [comment]
@jfly please tell me, until then I can't run tnoodle on my pc either!

**Comment by cubetastic33** [comment]
@jfly oh, never mind! I ran `./tmt make run -p wca`, then got yarn, then again executed the command, and after a few tries, I managed to get it working. Is this what you meant? I went to localhost:2014 as the logs in the terminal told me, and it said I needed to upgrade to the latest version, and that seems to be a java file. However, I then went to localhost:2014/readme, and found instructions for the API. Things are much clearer to me now! Going to this (http://localhost:2014/scramble/.txt?=333) link generates a scramble even without an Internet connection :smiley: I think this is what you meant... If it is, thanks a ton! You were really helpful!!

**Comment by jfly** [comment]
Glad you figure it out! I think it would be easiest for you to just download and run the tnoodle jar file directly. Since you're not modifying tnoodle yourself, there's no reason for you to be compiling it yourself.

**Comment by cubetastic33** [comment]
@jfly Oh no, I can't get it to work on my raspberry pi. It has an ARMv6 CPU, so I think the node js version is outdated. This is the output:
```
$ ./tmt make run -p wca
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error bootstrap@4.0.0-beta.2: The engine "node" is incompatible with this module. Expected version ">=6".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Hit excepthook! stderr.isatty: True stdin.isatty: True stdout.isatty: True
Traceback (most recent call last):
  File "./tmt", line 1220, in <module>
    tmt._main()
  File "./tmt", line 231, in _main
    self.args.func()
  File "./tmt", line 293, in _make
    commandFunc()
  File "./tmt", line 1159, in run
    self._rebuildTNoodleUI()
  File "./tmt", line 1040, in _rebuildTNoodleUI
    assert 0 == os.system(rebuildTNoodleUiCmd)
AssertionError
> /home/pi/Desktop/tnoodle/tmt(1040)_rebuildTNoodleUI()
-> assert 0 == os.system(rebuildTNoodleUiCmd)
(Pdb)
```
Please tell me what to do!

**Comment by cubetastic33** [comment]
@jfly after looking for a while, I found some repositories with newer node js versions for the pi 0, so I managed to get node js 8.0.0 on my rpi 0 W, but tnoodle is still not running.
It comes to this screen:
```
$ ./tmt make run -p wca
yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 24.66s.
yarn run v1.3.2
$ yarn run build-css && NODE_PATH=src react-scripts build
$ node-sass src/ -o src/
Rendering Complete, saving .css file...
Wrote CSS to /home/pi/Desktop/tnoodle/tnoodle-ui/src/Layout.css
Wrote 1 CSS files to /home/pi/Desktop/tnoodle/tnoodle-ui/src/
Creating an optimized production build...

```
And then everything gets stuck there. I tried waiting for hours, but still nothing happened. Please tell me what to do! I also tried copying the .jar file on my pc to the pi, but it just shows up as an archive. Also, I think that would be a 64bit version. Is there any precompiled thing that I could use?

**Comment by viroulep** [comment]
I don't get why you're still trying to *build* TNoodle when you're not going to do any change to it. There are plenty of releases available [there](https://github.com/thewca/tnoodle/releases).

I also don't get the 64 bit reference, the whole point of jar files is to contain platform independent bytecode, so talking about a possible 32/64 bit distinction for it makes no sense.

Here is what I would do in your situation: if your raspberry pi has access to internet, then just run `wget https://github.com/thewca/tnoodle/releases/download/v0.13.2/TNoodle-WCA-0.13.2.jar` and it will download the current 0.13.2 version.
After this you don't need a network connection anymore.
You can just start TNoodle using `java -jar TNoodle-WCA-0.13.2.jar`. It will create a *local* webserver that you can talk to as Jeremy explained, and that you successfully managed to use on your computer by visiting http://localhost:2014/scramble/.txt?=333.

Hopefully it will be far less painful than trying to startup a developer version of TNoodle!

**Comment by cubetastic33** [comment]
@viroulep wow, am I an idiot. I don't know much about java, so I thought there was a difference between the 64bit and 32 bit versions. Also, I forgot that there is a jar file available at the wca website. I _also_ didn't know how to run java files. In ubuntu, I just make sure it has the necessary permissions, and then double click it. As this wasn't the case on my RPi, I didn't know what to do.

**Comment by viroulep** [comment]
> so I thought there was a difference between the 64bit and 32 bit versions

It depends on what you refer too: the jvm (java virtual machine), the thing that runs jar files on your computer, comes in multiple versions depending on which architecture you want to use it on (eg: 32 bit, 64 bit), because it needs to adapt to the hardware it's running on (eg: the size of memory addresses, registers, ALUs, ...).
However the java program binary (the jar file) is using java bytecode, and it's just one single instruction set, hardware-oblivious.

Which is why java is popular, and why we chose it for TNoodle: you create one single binary, and it can run on everyone's computer that has a jvm (including raspberry pi :p).
Given our Delegates use a combination of Linux, Windows, and Mac, being platform independent was a requirement.

> I also didn't know how to run java files. In ubuntu, I just make sure it has the necessary permissions, and then double click it. As this wasn't the case on my RPi, I didn't know what to do.

Oh sorry, actually @campos20 mentioned how to run a jar file, so I thought you would know that.
Could you make it work then?

**Comment by cubetastic33** [comment]
@viroulep yeah, thanks a lot for the help! I didn't realise that is what campos meant when he said `java -jar scrambles.jar 333` Now, finally, thanks to all of you guys, I managed to generate wca scrambles on my rpi! I will tell you once I manage to get all of this working with python and showing on my lcd.

**Comment by cubetastic33** [comment]
@jfly, @viroulep, @campos20, thanks a lot guys, managed to get tnoodle scrambles on my lcd! 👍 👍 😄

**Comment by jfly** [comment]
Let's see a picture!

**Comment by cubetastic33** [comment]
@jfly The backlight was too bright in the picture, so I just took another without the backlight:
![image](https://user-images.githubusercontent.com/33519300/35780658-baa8dd30-0a04-11e8-9f30-fd4c4968b107.png)
