### ISSUE TITLE
OutOfMemoryError on Tnoodle 1.0.0

### ISSUE THREAD

**Issue by Goosly** [thewca/tnoodle#588]
I got an OutOfMemoryError (twice) on Tnoodle 1.0.0
I was playing with Manual Selection and setting "Scramble sets" or "Copies" to a ridiculously high number (1 million or higher)

This can probably be avoided by adding reasonable validation to these number input fields.

Here is the full logging:

`2020-07-29 17:47:09,531 INFO [main] o.w.t.s.w.s.MainLauncher [MainLauncher.kt:54] Detected os: Windows 10
2020-07-29 17:47:09,535 WARN [main] o.w.t.s.w.s.MainLauncher [MainLauncher.kt:134] C:\Program Files\Java\jre1.8.0_201\temp-launcher is not a directory.
2020-07-29 17:47:09,536 INFO [main] o.w.t.s.w.s.MainLauncher [MainLauncher.kt:60] needsReExecing: false
2020-07-29 17:47:10,213 INFO [main] d.s.SystemTray [SystemTray.java:1101] Successfully loaded
2020-07-29 17:47:10,215 WARN [main] d.s.SystemTray [MenuItem.java:370] Please disable tooltips, as they are not consistent across all platforms and tray types.
2020-07-29 17:47:12,482 INFO [main] Application [ApplicationEngineEnvironmentReloading.kt:135] No ktor.deployment.watch patterns specified, automatic reload is not active
2020-07-29 17:47:12,838 INFO [main] Application [BaseApplicationEngine.kt:39] Responding at http://0.0.0.0:2014
2020-07-29 17:47:13,308 INFO [main] o.w.t.s.w.WebscramblesServer [WebscramblesServer.kt:135] TNoodle-WCA-1.0.0 started
2020-07-29 17:47:13,309 INFO [main] o.w.t.s.w.s.OfflineJarUtils [OfflineJarUtils.kt:24] Attempting to open http://localhost:2014 in browser.
2020-07-29 17:47:13,511 INFO [main] o.w.t.s.w.WebscramblesServer [WebscramblesServer.kt:138] Visit http://localhost:2014 for a readme and demo.
2020-07-29 17:49:44,078 ERROR [nioEventLoopGroup-4-5] Application [DefaultEnginePipeline.kt:106] Unhandled: POST - /wcif/zip
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.io.ByteArrayOutputStream.grow(Unknown Source)
	at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
	at java.io.ByteArrayOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at java.io.FilterOutputStream.write(Unknown Source)
	at com.itextpdf.text.pdf.OutputStreamCounter.write(OutputStreamCounter.java:104)
	at com.itextpdf.text.pdf.PdfIndirectObject.writeTo(PdfIndirectObject.java:158)
	at com.itextpdf.text.pdf.PdfWriter$PdfBody.write(PdfWriter.java:402)
	at com.itextpdf.text.pdf.PdfWriter$PdfBody.add(PdfWriter.java:380)
	at com.itextpdf.text.pdf.PdfWriter$PdfBody.add(PdfWriter.java:355)
	at com.itextpdf.text.pdf.PdfWriter$PdfBody.add(PdfWriter.java:351)
	at com.itextpdf.text.pdf.PdfWriter.addToBody(PdfWriter.java:825)
	at com.itextpdf.text.pdf.PdfCopy.addToBody(PdfCopy.java:856)
	at com.itextpdf.text.pdf.PdfCopy.addToBody(PdfCopy.java:838)
	at com.itextpdf.text.pdf.PdfPages.addPage(PdfPages.java:89)
	at com.itextpdf.text.pdf.PdfCopy.addPage(PdfCopy.java:686)
	at com.itextpdf.text.pdf.PdfSmartCopy.addPage(PdfSmartCopy.java:168)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.MergedPdfWithOutline.writeContents(MergedPdfWithOutline.kt:36)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.MergedPdfWithOutline.writeContents(MergedPdfWithOutline.kt:7)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.BasePdfSheet.directRender(BasePdfSheet.kt:28)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.BasePdfSheet.render(BasePdfSheet.kt:14)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.PdfContent$DefaultImpls.render$default(PdfContent.kt:4)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.folder.PrintingFolder$assemble$1.invoke(PrintingFolder.kt:90)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.folder.PrintingFolder$assemble$1.invoke(PrintingFolder.kt:21)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.DSLKt.folder(DSL.kt:39)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.folder.PrintingFolder.assemble(PrintingFolder.kt:31)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.ScrambleZip.assemble(ScrambleZip.kt:22)
	at org.worldcubeassociation.tnoodle.server.webscrambles.wcif.WCIFDataBuilder.requestsToZip(WCIFDataBuilder.kt:109)
	at org.worldcubeassociation.tnoodle.server.webscrambles.wcif.WCIFDataBuilder.wcifToZip(WCIFDataBuilder.kt:104)
	at org.worldcubeassociation.tnoodle.server.webscrambles.routing.WcifHandler$install$1$2$job$1.invokeSuspend(WcifHandler.kt:64)
2020-07-29 18:10:01,397 INFO [main] o.w.t.s.w.s.MainLauncher [MainLauncher.kt:54] Detected os: Windows 10
2020-07-29 18:10:01,401 WARN [main] o.w.t.s.w.s.MainLauncher [MainLauncher.kt:134] C:\Program Files\Java\jre1.8.0_201\temp-launcher is not a directory.
2020-07-29 18:10:01,401 INFO [main] o.w.t.s.w.s.MainLauncher [MainLauncher.kt:60] needsReExecing: false
2020-07-29 18:10:01,885 INFO [main] d.s.SystemTray [SystemTray.java:1101] Successfully loaded
2020-07-29 18:10:01,887 WARN [main] d.s.SystemTray [MenuItem.java:370] Please disable tooltips, as they are not consistent across all platforms and tray types.
2020-07-29 18:10:04,032 INFO [main] Application [ApplicationEngineEnvironmentReloading.kt:135] No ktor.deployment.watch patterns specified, automatic reload is not active
2020-07-29 18:10:04,357 INFO [main] Application [BaseApplicationEngine.kt:39] Responding at http://0.0.0.0:2014
2020-07-29 18:10:04,809 INFO [main] o.w.t.s.w.WebscramblesServer [WebscramblesServer.kt:135] TNoodle-WCA-1.0.0 started
2020-07-29 18:10:04,810 INFO [main] o.w.t.s.w.s.OfflineJarUtils [OfflineJarUtils.kt:24] Attempting to open http://localhost:2014 in browser.
2020-07-29 18:10:04,990 INFO [main] o.w.t.s.w.WebscramblesServer [WebscramblesServer.kt:138] Visit http://localhost:2014 for a readme and demo.
2020-07-29 18:12:52,536 ERROR [nioEventLoopGroup-4-3] Application [DefaultEnginePipeline.kt:106] Unhandled: POST - /wcif/zip
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.io.ByteArrayOutputStream.grow(Unknown Source)
	at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
	at java.io.ByteArrayOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at com.itextpdf.text.pdf.OutputStreamCounter.write(OutputStreamCounter.java:124)
	at com.itextpdf.text.pdf.PdfDictionary.toPdf(PdfDictionary.java:157)
	at com.itextpdf.text.pdf.PdfDictionary.toPdf(PdfDictionary.java:154)
	at com.itextpdf.text.pdf.PdfDictionary.toPdf(PdfDictionary.java:154)
	at com.itextpdf.text.pdf.PdfIndirectObject.writeTo(PdfIndirectObject.java:157)
	at com.itextpdf.text.pdf.PdfWriter$PdfBody.write(PdfWriter.java:402)
	at com.itextpdf.text.pdf.PdfWriter$PdfBody.add(PdfWriter.java:380)
	at com.itextpdf.text.pdf.PdfWriter$PdfBody.add(PdfWriter.java:355)
	at com.itextpdf.text.pdf.PdfWriter$PdfBody.add(PdfWriter.java:351)
	at com.itextpdf.text.pdf.PdfWriter.addToBody(PdfWriter.java:825)
	at com.itextpdf.text.pdf.PdfCopy.addToBody(PdfCopy.java:856)
	at com.itextpdf.text.pdf.PdfCopy.addToBody(PdfCopy.java:838)
	at com.itextpdf.text.pdf.PdfPages.addPage(PdfPages.java:89)
	at com.itextpdf.text.pdf.PdfCopy.addPage(PdfCopy.java:686)
	at com.itextpdf.text.pdf.PdfSmartCopy.addPage(PdfSmartCopy.java:168)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.MergedPdfWithOutline.writeContents(MergedPdfWithOutline.kt:36)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.MergedPdfWithOutline.writeContents(MergedPdfWithOutline.kt:7)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.BasePdfSheet.directRender(BasePdfSheet.kt:28)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.BasePdfSheet.render(BasePdfSheet.kt:14)
	at org.worldcubeassociation.tnoodle.server.webscrambles.pdf.PdfContent$DefaultImpls.render$default(PdfContent.kt:4)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.folder.PrintingFolder$assemble$1.invoke(PrintingFolder.kt:90)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.folder.PrintingFolder$assemble$1.invoke(PrintingFolder.kt:21)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.DSLKt.folder(DSL.kt:39)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.folder.PrintingFolder.assemble(PrintingFolder.kt:31)
	at org.worldcubeassociation.tnoodle.server.webscrambles.zip.ScrambleZip.assemble(ScrambleZip.kt:22)
	at org.worldcubeassociation.tnoodle.server.webscrambles.wcif.WCIFDataBuilder.requestsToZip(WCIFDataBuilder.kt:109)
`

**Comment by campos20** [comment]
@suushiemaniac do you want this validation to happen on the backend or on the frontend?

**Comment by suushiemaniac** [comment]
Hey @Goosly, thanks for the concise error report! This has been fixed (along with more beautiful error display) in https://github.com/thewca/tnoodle/pull/591
